name: easy-bazaar CICD

on:
  push:
    branches:
        - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use node js
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node-version}}
      - name: npm install and build
        run:  |
          npm install
          cd frontend
          npm install
          # npm run build
          # git config --global user.name "rahul"
          # git add build
          # git commit -m "build updated"
          # git push origin master -f
          # git pull origin master

        env:
          CI: true

  deploy:
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - name: SSH deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.USER}}
          key:  ${{secrets.KEY}}
          port: ${{secrets.PORT}}

          script: |
              cd MERN-Ecommerce
              git pull origin master
              npm install
              cd frontend
              npm install
              cd ..
              cd backend
              pm2 restart server.js     